[package]
name = "panic"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = 'abort'
#  on release when panic it will exit without cleaning after

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
